### ISSUE TITLE
Decompression failure on short bytestrings

### ISSUE THREAD

**Issue by LivInTheLookingGlass** [miurahr/ppmd#3]
**Describe the bug**
On small test strings, compressing then decompressing yields a truncated answer

**To Reproduce**
```python
>>> import ppmd
>>> enc = ppmd.PpmdBufferEncoder(5, 16 << 20)
>>> compressed = enc.encode(b'test') + enc.flush()
bytearray(b'\x00s\xef\x96\xfe\x86\x18\xda')
>>> ppmd.PpmdBufferDecoder(5, 16 << 20).decode(compressed, 1 << 10)
b'tes'
```

**Expected behavior**
It should return the original string

**Environment (please complete the following information):**
 - OS: Fedora (uname -a: `Linux Calypso 5.8.15-101.fc31.x86_64 #1 SMP Thu Oct 15 16:57:45 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`)
 - Python 3.7.9
 - py7zr version: 0.10.1

**Comment by miurahr** [comment]
Thank you for the report. When run following test cases, `test_short_string1`  is passed,  and `test_short_string_2` is failed.

Because `PpmdBufferDecoder` wraps `PpmdDecoder`, the bug relate with buffer handling in `PpmdBufferDecoder`. 

```

def test_short_string_1():
    source = b'test'
    enc = ppmd.PpmdBufferEncoder(5, 16 << 20)
    compressed = enc.encode(source) + enc.flush()
    f = io.BytesIO(compressed)
    assert ppmd.PpmdDecoder(f, 5, 16 << 20).decode(4) == source


def test_short_string_2():
    source = b'test'
    enc = ppmd.PpmdBufferEncoder(5, 16 << 20)
    compressed = enc.encode(source) + enc.flush()
    assert ppmd.PpmdBufferDecoder(5, 16 << 20).decode(compressed, 4) == source
```

**Comment by miurahr** [comment]
It is not a bug; following test code is passed.

```
def test_short_string_2():
    source = b'test'
    enc = ppmd.PpmdBufferEncoder(5, 16 << 20)
    compressed = enc.encode(source) + enc.flush()
    dec = ppmd.PpmdBufferDecoder(5, 16 << 20)
    result = dec.decode(compressed, 4)
    remaining = 4 - len(result)
    result += dec.decode(b'', remaining)
    assert result == source
```

decode() method does not always return specified `max_length`.

**Comment by miurahr** [comment]
Is it better to introduce `flush(size)` method as an alias of `decode(b'', size)`?

**Comment by miurahr** [comment]
and following code produce a string with 1024 bytes length.

```

def test_short_string_3():
    source = b'test'
    enc = ppmd.PpmdBufferEncoder(5, 16 << 20)
    compressed = enc.encode(source) + enc.flush()
    dec = ppmd.PpmdBufferDecoder(5, 16 << 20)
    length = 1 << 10
    result = dec.decode(compressed, length)
    remaining = length - len(result)
    result += dec.decode(b'', remaining)
    print(result)

```

This is a nature of PPMd algorithm.

**Comment by LivInTheLookingGlass** [comment]
Okay. So, to be clear, something like the following would work?

```python
def decompress_ppmd(foo: bytes) -> bytes:
    with ppmd.PpmdBufferDecoder(5, 16 << 20) as dec:
        ret = dec.decode(foo, 32 << 20)
        prev = b''
        while ret != prev:
            prev = ret
            ret += dec.decode(b'', 32 << 20)
        return ret
```

**Comment by miurahr** [comment]
@gappleto97  It would be produce ***infinite*** loops with chunk data of 32MB and never return or failed with memory error.

**Comment by miurahr** [comment]
It is recommended to use PpmdDecoder class instead of PpmdBufferDecoder class,  when you do not understand all what you are doing.

**Comment by LivInTheLookingGlass** [comment]
I'm going to assume you didn't intend an insulting tone there. Tone on the internet is hard, after all.

In any case, what I'm trying to get at is that every single other ones of the 20+ compression implementations I've looked at (I'm trying to make a common API package for all the different compression methods) this is the only one where there's no obvious way to decode the entirety of a string of unknown length.

The method I sketched above doesn't make an infinite loop unless your class is constantly outputting data. When I tested giving it an empty bytestring, it always either returned another empty bytestring or it returned additional data from the last non-empty one. If that is correct, then I don't see how it would be possible to infinite loop unless there were a bug in the library, or a misunderstanding on my part of what your methods do. Which, by the way, is not documented at all, so I don't think it's fair to complain that I don't understand it where I'm literally asking for clarification.

**Comment by miurahr** [comment]
PPMd code here is borrowed from p7zip implementation, which has an interface that give an output length at first.
The ppmd-cffi python module wrap it with same interface, that is PpmdDecoder.
I want to use buffer protocol over it, so I wrap it with buffer, that is PpmdBufferDecoder.

As a nature of original implementation, its behavior may be undefined when read unknown length of data.
In order to enable to call PpmdBufferDecode again and again, it processes input data for `len(data) - 1` and return.
When calling empty data `b''`, PpmdBufferDecode.read() consume all the input data and try to read data which length is specified in second argument.

PpmdBufferDecoder can not recognize input size is enough or not.  PpmdDecoder  has a same interface with original C implementation, which read input data from file object. When reaching EOF of input data, PPMd core function may stop reading and produce  data which it can be produced.

You seems having an use case that output length is unknown, so PPMd, at least the project here, may not be good  for it.

**Comment by miurahr** [comment]
> this is the only one where there's no obvious way to decode the entirety of a string of unknown length.

Here is a bare algorithm library which compress/decompress without container format, which may hold compression parameter, level/mem_size, data length and/or data checksum.

Original PPMd has its own container format which hold compression parameters, and length of data, but ppmd-cffi don't know it.

@gappleto97 you may need to see other library that support containers.

**Comment by miurahr** [comment]
IMHO, because I don't understand  PPMd algorithm enough, I might express wrongly.

The  C code here is derived from 7-zip implementation which assumes  an output length is given by caller. I use the library  for my  7-zip library on python that call ppmd library as same way as original 7-zip implementation.

So I might be not good at understandings of a behavior when decoding/reading the large length.

**Comment by miurahr** [comment]
You can use Ppmd8Decompressor class that take input file object and its size, and produce data for unknown output size in v0.3.0. Also you can use Ppmd8Compressor class to compression.

ref https://github.com/miurahr/ppmd/blob/main/src/ppmd/__init__.py#L250

Ppmd8Compressor produce data with compression parameters as header, and Ppmd8Decompressor recognize header and decompress its data.

**Comment by LivInTheLookingGlass** [comment]
I'll make sure to take a look at this over the weekend and confirm with you if the wrapper I write will produce correct behavior.

Thank you for being patient with me. I wanted to make sure I apologize for my rudeness in my earlier comments. I've been having a really bad time lately and I think I took it out on you a little. I'll try to be better in the future.

**Comment by miurahr** [comment]
No feedback in 6 month.
